-- =====================================================
-- Docker 初始化 SQL - 工装管理系统
-- MySQL 8.0+ / utf8mb4
-- docker-compose 已自动创建 vue_back 数据库并切换
-- =====================================================

-- =====================================================
-- 1. 用户表
-- =====================================================
CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    username VARCHAR(50) NOT NULL UNIQUE COMMENT '用户名',
    password VARCHAR(255) NOT NULL COMMENT '密码(BCrypt加密)',
    email VARCHAR(100) COMMENT '邮箱',
    role VARCHAR(20) DEFAULT 'USER' COMMENT '角色(ADMIN/USER)',
    status VARCHAR(10) DEFAULT '在线' COMMENT '状态',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统用户表';

INSERT IGNORE INTO sys_user (username, password, email, role, status) VALUES
('admin', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'admin@example.com', 'ADMIN', '在线'),
('user', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'user@example.com', 'USER', '在线');

-- =====================================================
-- 物资来源字典表
-- =====================================================
CREATE TABLE IF NOT EXISTS T_MATERIAL_SOURCES (
    CODE VARCHAR(2) NOT NULL PRIMARY KEY COMMENT '来源编码(01:采购, 02:库存, 03:自制)',
    NAME VARCHAR(50) NOT NULL COMMENT '来源名称',
    SORT_ORDER INT DEFAULT 0 COMMENT '排序',
    STATUS VARCHAR(2) DEFAULT '01' COMMENT '状态(01:有效, 02:无效)'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='物资来源字典表';

INSERT IGNORE INTO T_MATERIAL_SOURCES (CODE, NAME, SORT_ORDER, STATUS) VALUES
('01', '采购', 1, '01'),
('02', '库存', 2, '01'),
('03', '自制', 3, '01');

-- =====================================================
-- 钢材材质字典表
-- =====================================================
CREATE TABLE IF NOT EXISTS T_BASIC_STEEL_QUALITY (
    CODE VARCHAR(50) NOT NULL PRIMARY KEY COMMENT '材质编码',
    NAME VARCHAR(200) NOT NULL COMMENT '材质名称',
    STATUS VARCHAR(2) DEFAULT '01' COMMENT '状态(01:有效, 02:无效)',
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='钢材材质字典表';

INSERT IGNORE INTO T_BASIC_STEEL_QUALITY (CODE, NAME, STATUS) VALUES
('Q235', 'Q235碳素结构钢', '01'),
('Q345', 'Q345低合金高强度钢', '01'),
('45#', '45#优质碳素钢', '01'),
('40Cr', '40Cr合金结构钢', '01'),
('304', '304不锈钢', '01'),
('316L', '316L不锈钢', '01'),
('2A12', '2A12硬铝合金', '01'),
('H62', 'H62黄铜', '01');

-- =====================================================
-- 附件类型字典表
-- =====================================================
CREATE TABLE IF NOT EXISTS T_ATTACHMENT_TYPE (
    CODE VARCHAR(2) NOT NULL PRIMARY KEY COMMENT '类型编码',
    NAME VARCHAR(50) NOT NULL COMMENT '类型名称',
    STATUS VARCHAR(2) DEFAULT '01' COMMENT '状态'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='附件类型字典表';

INSERT IGNORE INTO T_ATTACHMENT_TYPE (CODE, NAME, STATUS) VALUES
('01', '设计图纸', '01'),
('02', '材料清单', '01'),
('03', '技术规范', '01'),
('04', '审批文件', '01'),
('99', '其他', '01');

-- =====================================================
-- 工装申请主表 T_COMPONENTS
-- =====================================================
CREATE TABLE IF NOT EXISTS T_COMPONENTS (
    GUID VARCHAR(64) NOT NULL COMMENT '唯一标识GUID',
    BILL_NO VARCHAR(50) NOT NULL COMMENT '申请单号',
    COMPANY_NO VARCHAR(50) COMMENT '公司主体代码',
    DEPT_NO VARCHAR(50) COMMENT '申请部门代码',
    COMPONENTS_NAME VARCHAR(200) COMMENT '项目名称',
    PROJ_NO VARCHAR(50) COMMENT '工程号',
    DIV_CD VARCHAR(2) COMMENT '工装类别代码: 01-生产通用,02-生产专用,03-安措,04-科研通用,05-科研专用',
    NUMBER_NO DECIMAL(10,2) DEFAULT 0 COMMENT '申请数量',
    FINAL_NUMBER_NO DECIMAL(10,2) DEFAULT 0 COMMENT '最终审核数',
    APPOINT_DUTY_DEPT_YN VARCHAR(1) COMMENT '是否指定责任部门',
    DWGNO VARCHAR(100) COMMENT '图号',
    MATERIAL_TOTAL_COST VARCHAR(100) COMMENT '材料总成本',
    MH_BDGT VARCHAR(100) COMMENT '人工预算',
    CREATE_USER_ID VARCHAR(50) COMMENT '创建用户ID',
    CREATE_DATE DATE COMMENT '创建日期',
    NEED_DATE DATE COMMENT '需求日期',
    UPDATE_USER_ID VARCHAR(50) COMMENT '更新用户ID',
    UPDATE_DATE DATE COMMENT '更新日期',
    REMARK VARCHAR(500) COMMENT '备注',
    MA_PROCESS_ID VARCHAR(100) COMMENT '流程ID(BPM流程实例ID)',
    MA_STATUS VARCHAR(2) DEFAULT '01' COMMENT '申请状态: 00-退回, 01-编制, 02-审批, 03-完成, 04-设计出图, 05-设计出图审批',
    TEL VARCHAR(50) COMMENT '联系电话',
    APP_DATE DATE COMMENT '申请日期',
    DESIGN_STATUS VARCHAR(2) COMMENT '设计状态',
    BO_ID VARCHAR(100) COMMENT '业务对象ID',
    PRIMARY KEY (GUID),
    UNIQUE KEY UK_BILL_NO (BILL_NO),
    KEY IDX_COMPANY_NO (COMPANY_NO),
    KEY IDX_DEPT_NO (DEPT_NO),
    KEY IDX_PROJ_NO (PROJ_NO),
    KEY IDX_MA_STATUS (MA_STATUS),
    KEY IDX_CREATE_DATE (CREATE_DATE),
    KEY IDX_CREATE_USER_ID (CREATE_USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='工装申请表';

-- =====================================================
-- 工装申请明细表 T_COMPONENTS_LINE
-- =====================================================
CREATE TABLE IF NOT EXISTS T_COMPONENTS_LINE (
    GUID VARCHAR(64) NOT NULL COMMENT '唯一标识GUID',
    COMPONENTS_ID VARCHAR(64) NOT NULL COMMENT '工装申请ID(外键->T_COMPONENTS.GUID)',
    ACTIVATION VARCHAR(100) COMMENT '激活/生效标识',
    MATERIAL_NO VARCHAR(50) COMMENT '物资编码',
    MATERIAL_NAME VARCHAR(200) COMMENT '物资名称',
    UNIT VARCHAR(50) COMMENT '单位',
    DEMAND_QTY DECIMAL(10,2) DEFAULT 0 COMMENT '需求数量',
    FINAL_DEMAND_QTY DECIMAL(10,2) DEFAULT 0 COMMENT '最终需求数量',
    MATERIAL_COST DECIMAL(10,2) COMMENT '材料成本',
    MATERIAL_SOURCES VARCHAR(50) COMMENT '物资来源',
    REMARK VARCHAR(500) COMMENT '备注',
    QUALITY VARCHAR(100) COMMENT '材质/质量等级',
    THK1 DECIMAL(10,2) COMMENT '厚度1',
    THK2 DECIMAL(10,2) COMMENT '厚度2',
    W1 DECIMAL(10,2) COMMENT '宽度1',
    W2 DECIMAL(10,2) COMMENT '宽度2',
    L DECIMAL(10,2) COMMENT '长度',
    CREATE_NODE VARCHAR(100) COMMENT '创建节点',
    CREATE_USER_ID VARCHAR(50) COMMENT '创建用户ID',
    CREATE_DATE DATE COMMENT '创建日期',
    UPDATE_USER_ID VARCHAR(50) COMMENT '更新用户ID',
    UPDATE_DATE DATE COMMENT '更新日期',
    BO_ID VARCHAR(100) COMMENT '业务对象ID',
    PRIMARY KEY (GUID),
    KEY IDX_COMPONENTS_ID (COMPONENTS_ID),
    KEY IDX_MATERIAL_NO (MATERIAL_NO),
    KEY IDX_CREATE_DATE (CREATE_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='工装申请明细表';

-- =====================================================
-- 工装附件表 T_COMPONENTS_ATT
-- =====================================================
CREATE TABLE IF NOT EXISTS T_COMPONENTS_ATT (
    GUID VARCHAR(64) NOT NULL COMMENT '唯一标识GUID',
    COMPONENTS_ID VARCHAR(64) COMMENT '工装申请ID(外键->T_COMPONENTS.GUID)',
    FILE_NAME VARCHAR(200) COMMENT '文件名',
    FILE_PATH VARCHAR(500) COMMENT '文件路径',
    FILE_SIZE VARCHAR(50) COMMENT '文件大小',
    FILE_TYPE VARCHAR(50) COMMENT '文件类型',
    CREATE_USER_ID VARCHAR(50) COMMENT '创建用户ID',
    CREATE_DATE DATE COMMENT '创建日期',
    UPDATE_USER_ID VARCHAR(50) COMMENT '更新用户ID',
    UPDATE_DATE DATE COMMENT '更新日期',
    REMARK VARCHAR(500) COMMENT '备注',
    PRIMARY KEY (GUID),
    KEY IDX_COMPONENTS_ID (COMPONENTS_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='工装申请附件表';

-- =====================================================
-- 工装申请审批意见表 T_COMPONENTS_OPINION
-- =====================================================
CREATE TABLE IF NOT EXISTS T_COMPONENTS_OPINION (
    GUID VARCHAR(64) NOT NULL COMMENT '唯一标识GUID',
    COMPONENTS_ID VARCHAR(64) COMMENT '工装申请ID(外键->T_COMPONENTS.GUID)',
    OPINION_TYPE VARCHAR(2) COMMENT '意见类型',
    OPINION_CONTENT VARCHAR(1000) COMMENT '意见内容',
    AUDIT_USER_ID VARCHAR(50) COMMENT '审核人ID',
    AUDIT_USER_NAME VARCHAR(100) COMMENT '审核人姓名',
    AUDIT_DATE DATE COMMENT '审核日期',
    CREATE_USER_ID VARCHAR(50) COMMENT '创建用户ID',
    CREATE_DATE DATE COMMENT '创建日期',
    UPDATE_USER_ID VARCHAR(50) COMMENT '更新用户ID',
    UPDATE_DATE DATE COMMENT '更新日期',
    PRIMARY KEY (GUID),
    KEY IDX_COMPONENTS_ID (COMPONENTS_ID),
    KEY IDX_AUDIT_USER_ID (AUDIT_USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='工装申请审批意见表';

-- =====================================================
-- 附件数据表 T_COMPONENTS_ATT_DATA
-- =====================================================
CREATE TABLE IF NOT EXISTS T_COMPONENTS_ATT_DATA (
    GUID VARCHAR(64) NOT NULL PRIMARY KEY COMMENT 'GUID',
    ATT_ID VARCHAR(64) COMMENT '附件ID(FK->T_COMPONENTS_ATT.GUID)',
    FILE_DATA LONGBLOB COMMENT '文件二进制数据',
    CREATE_USER_ID VARCHAR(50) COMMENT '创建人',
    CREATE_DATE DATE COMMENT '创建日期',
    KEY IDX_ATT_ID (ATT_ID),
    CONSTRAINT FK_ATTDATA_ATT FOREIGN KEY (ATT_ID) REFERENCES T_COMPONENTS_ATT(GUID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='工装申请附件数据表';

-- =====================================================
-- 引用/报价表 T_COMPONENTS_QUOTE
-- =====================================================
CREATE TABLE IF NOT EXISTS T_COMPONENTS_QUOTE (
    GUID VARCHAR(64) NOT NULL PRIMARY KEY COMMENT 'GUID',
    COMPONENT_ID VARCHAR(64) COMMENT '工装ID(FK->T_COMPONENTS.GUID)',
    IS_USED VARCHAR(2) COMMENT '是否使用(01:是,02:否)',
    IS_QUOTED VARCHAR(2) COMMENT '是否被引用(01:否,02:是)',
    COM_DATE DATE COMMENT '完成日期',
    CREATE_USER_ID VARCHAR(50) COMMENT '创建人',
    CREATE_DATE DATE COMMENT '创建日期',
    UPDATE_USER_ID VARCHAR(50) COMMENT '更新人',
    UPDATE_DATE DATE COMMENT '更新日期',
    REMARK VARCHAR(500) COMMENT '备注',
    KEY IDX_COMPONENT_ID (COMPONENT_ID),
    CONSTRAINT FK_QUOTE_COMPONENTS FOREIGN KEY (COMPONENT_ID) REFERENCES T_COMPONENTS(GUID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='工装申请引用/报价表';

-- =====================================================
-- 工装台账主表 T_COMPONENTS_LEDGER
-- =====================================================
CREATE TABLE IF NOT EXISTS T_COMPONENTS_LEDGER (
    GUID VARCHAR(64) NOT NULL PRIMARY KEY COMMENT 'GUID',
    COMPONENT_GUID VARCHAR(64) COMMENT '关联工装申请ID(FK->T_COMPONENTS.GUID)',
    BILL_NO VARCHAR(50) COMMENT '台账单据号',
    TYPE_CODE VARCHAR(50) COMMENT '台账类型(FK->T_COMPONENTS_LEDGER_TYPE.CODE)',
    COMPANY_NO VARCHAR(50) COMMENT '公司编码',
    DEPT_NO VARCHAR(50) COMMENT '部门编码',
    COMPONENTS_NAME VARCHAR(200) COMMENT '工装名称',
    SPECIFICATION VARCHAR(200) COMMENT '规格型号',
    QUANTITY DECIMAL(10,2) DEFAULT 0 COMMENT '数量',
    UNIT VARCHAR(50) COMMENT '单位',
    LOCATION VARCHAR(200) COMMENT '存放位置',
    STATUS VARCHAR(2) DEFAULT '01' COMMENT '状态(01:在库,02:借出,03:维修,04:报废)',
    BORROW_DEPT VARCHAR(100) COMMENT '借用部门',
    BORROW_PERSON VARCHAR(50) COMMENT '借用人',
    BORROW_DATE DATE COMMENT '借出日期',
    EXPECTED_RETURN_DATE DATE COMMENT '预计归还日期',
    ACTUAL_RETURN_DATE DATE COMMENT '实际归还日期',
    REMARK VARCHAR(500) COMMENT '备注',
    CREATE_USER_ID VARCHAR(50) COMMENT '创建人',
    CREATE_DATE DATE COMMENT '创建日期',
    UPDATE_USER_ID VARCHAR(50) COMMENT '更新人',
    UPDATE_DATE DATE COMMENT '更新日期',
    KEY IDX_COMPONENT_GUID (COMPONENT_GUID),
    KEY IDX_BILL_NO (BILL_NO),
    KEY IDX_TYPE_CODE (TYPE_CODE),
    KEY IDX_STATUS (STATUS),
    KEY IDX_BORROW_DEPT (BORROW_DEPT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='工装台账主表';

-- =====================================================
-- 台账明细表 T_COMPONENTS_LEDGER_LIST
-- =====================================================
CREATE TABLE IF NOT EXISTS T_COMPONENTS_LEDGER_LIST (
    GUID VARCHAR(64) NOT NULL PRIMARY KEY COMMENT 'GUID',
    LEDGER_GUID VARCHAR(64) NOT NULL COMMENT '台账主表ID(FK->T_COMPONENTS_LEDGER.GUID)',
    ITEM_NO INT DEFAULT 0 COMMENT '序号',
    COMPONENTS_NAME VARCHAR(200) COMMENT '工装名称',
    SPECIFICATION VARCHAR(200) COMMENT '规格型号',
    QUANTITY DECIMAL(10,2) DEFAULT 0 COMMENT '数量',
    UNIT VARCHAR(50) COMMENT '单位',
    REMARK VARCHAR(500) COMMENT '备注',
    CREATE_USER_ID VARCHAR(50) COMMENT '创建人',
    CREATE_DATE DATE COMMENT '创建日期',
    KEY IDX_LEDGER_GUID (LEDGER_GUID),
    CONSTRAINT FK_LIST_LEDGER FOREIGN KEY (LEDGER_GUID) REFERENCES T_COMPONENTS_LEDGER(GUID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='台账明细表';

-- =====================================================
-- 台账汇总表 T_COMPONENTS_LEDGER_GATHER
-- =====================================================
CREATE TABLE IF NOT EXISTS T_COMPONENTS_LEDGER_GATHER (
    GUID VARCHAR(64) NOT NULL PRIMARY KEY COMMENT 'GUID',
    TYPE_CODE VARCHAR(50) COMMENT '台账类型(FK->T_COMPONENTS_LEDGER_TYPE.CODE)',
    COMPANY_NO VARCHAR(50) COMMENT '公司编码',
    TOTAL_COUNT DECIMAL(10,2) DEFAULT 0 COMMENT '总数量',
    BORROWED_COUNT DECIMAL(10,2) DEFAULT 0 COMMENT '已借出数量',
    AVAILABLE_COUNT DECIMAL(10,2) DEFAULT 0 COMMENT '可用数量',
    MAINTENANCE_COUNT DECIMAL(10,2) DEFAULT 0 COMMENT '维修中数量',
    SCRAPPED_COUNT DECIMAL(10,2) DEFAULT 0 COMMENT '已报废数量',
    STATISTICS_DATE DATE COMMENT '统计日期',
    CREATE_DATE DATE COMMENT '创建日期',
    KEY IDX_TYPE_CODE (TYPE_CODE),
    KEY IDX_STATISTICS_DATE (STATISTICS_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='台账汇总表';

-- =====================================================
-- 台账单据表 T_COMPONENTS_LEDGER_BILL
-- =====================================================
CREATE TABLE IF NOT EXISTS T_COMPONENTS_LEDGER_BILL (
    GUID VARCHAR(64) NOT NULL PRIMARY KEY COMMENT 'GUID',
    BILL_NO VARCHAR(50) NOT NULL COMMENT '单据号',
    TYPE_CODE VARCHAR(50) COMMENT '台账类型(FK->T_COMPONENTS_LEDGER_TYPE.CODE)',
    COMPANY_NO VARCHAR(50) COMMENT '公司编码',
    BILL_TYPE VARCHAR(2) COMMENT '单据类型(01:入库,02:出库,03:退库)',
    BILL_DATE DATE COMMENT '单据日期',
    BORROW_DEPT VARCHAR(100) COMMENT '借用部门',
    BORROW_PERSON VARCHAR(50) COMMENT '借用人',
    ALLOT_DEPT VARCHAR(100) COMMENT '调拨部门',
    HANDLER VARCHAR(50) COMMENT '经办人',
    STATUS VARCHAR(2) DEFAULT '01' COMMENT '状态(01:待审批,02:已审批,03:已完成)',
    REMARK VARCHAR(500) COMMENT '备注',
    CREATE_USER_ID VARCHAR(50) COMMENT '创建人',
    CREATE_DATE DATE COMMENT '创建日期',
    UPDATE_USER_ID VARCHAR(50) COMMENT '更新人',
    UPDATE_DATE DATE COMMENT '更新日期',
    KEY IDX_BILL_NO (BILL_NO),
    KEY IDX_TYPE_CODE (TYPE_CODE),
    KEY IDX_BILL_TYPE (BILL_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='台账单据表';

-- =====================================================
-- 台账类型表 T_COMPONENTS_LEDGER_TYPE
-- =====================================================
CREATE TABLE IF NOT EXISTS T_COMPONENTS_LEDGER_TYPE (
    CODE VARCHAR(50) NOT NULL PRIMARY KEY COMMENT '类型编码',
    NAME VARCHAR(200) NOT NULL COMMENT '类型名称',
    STATUS VARCHAR(2) DEFAULT '01' COMMENT '状态(01:有效,02:无效)',
    SORT_ORDER INT DEFAULT 0 COMMENT '排序',
    CREATE_DATE DATE COMMENT '创建日期',
    REMARK VARCHAR(500) COMMENT '备注'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='台账类型表';

INSERT IGNORE INTO T_COMPONENTS_LEDGER_TYPE (CODE, NAME, STATUS, SORT_ORDER) VALUES
('TYPE01', '焊接工装', '01', 1),
('TYPE02', '装配工装', '01', 2),
('TYPE03', '检测工装', '01', 3),
('TYPE04', '吊具工装', '01', 4),
('TYPE05', '机加工工装', '01', 5);

-- =====================================================
-- 台账审批意见表 T_COMPONENTS_LEDGER_OPINION
-- =====================================================
CREATE TABLE IF NOT EXISTS T_COMPONENTS_LEDGER_OPINION (
    GUID VARCHAR(64) NOT NULL PRIMARY KEY COMMENT 'GUID',
    BILL_GUID VARCHAR(64) COMMENT '单据ID(FK->T_COMPONENTS_LEDGER_BILL.GUID)',
    OPINION_CONTENT VARCHAR(1000) COMMENT '意见内容',
    AUDIT_USER_ID VARCHAR(50) COMMENT '审核人ID',
    AUDIT_USER_NAME VARCHAR(100) COMMENT '审核人姓名',
    AUDIT_DATE DATE COMMENT '审核日期',
    AUDIT_RESULT VARCHAR(2) COMMENT '审核结果(01:同意,02:驳回)',
    CREATE_DATE DATE COMMENT '创建日期',
    KEY IDX_BILL_GUID (BILL_GUID),
    CONSTRAINT FK_OPINION_BILL FOREIGN KEY (BILL_GUID) REFERENCES T_COMPONENTS_LEDGER_BILL(GUID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='台账审批意见表';

-- =====================================================
-- 台账附件表 T_COMPONENTS_LEDGER_ATT
-- =====================================================
CREATE TABLE IF NOT EXISTS T_COMPONENTS_LEDGER_ATT (
    GUID VARCHAR(64) NOT NULL PRIMARY KEY COMMENT 'GUID',
    BILL_GUID VARCHAR(64) COMMENT '单据ID(FK->T_COMPONENTS_LEDGER_BILL.GUID)',
    FILE_NAME VARCHAR(200) NOT NULL COMMENT '文件名称',
    FILE_PATH VARCHAR(500) NOT NULL COMMENT '文件路径',
    FILE_SIZE VARCHAR(50) COMMENT '文件大小',
    CREATE_USER_ID VARCHAR(50) COMMENT '上传人',
    CREATE_DATE DATE COMMENT '上传日期',
    KEY IDX_BILL_GUID (BILL_GUID),
    CONSTRAINT FK_ATT_BILL FOREIGN KEY (BILL_GUID) REFERENCES T_COMPONENTS_LEDGER_BILL(GUID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='台账附件表';

-- =====================================================
-- 审批流程配置表 T_APPROVAL_FLOW
-- =====================================================
CREATE TABLE IF NOT EXISTS T_APPROVAL_FLOW (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
    FLOW_NAME VARCHAR(100) NOT NULL COMMENT '流程名称',
    STEP_ORDER INT NOT NULL COMMENT '步骤顺序',
    STEP_NAME VARCHAR(100) NOT NULL COMMENT '步骤名称',
    APPROVER_ROLE VARCHAR(50) COMMENT '审批人角色',
    APPROVER_ID VARCHAR(50) COMMENT '审批人ID',
    STATUS VARCHAR(2) DEFAULT '01' COMMENT '状态(01:有效,02:无效)'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='审批流程配置表';

INSERT IGNORE INTO T_APPROVAL_FLOW (FLOW_NAME, STEP_ORDER, STEP_NAME, APPROVER_ROLE) VALUES
('工装申请审批', 1, '部门主管审批', 'DEPT_MANAGER'),
('工装申请审批', 2, '技术主管审批', 'TECH_MANAGER'),
('工装申请审批', 3, '总经理审批', 'GENERAL_MANAGER');

-- =====================================================
-- 用户页面权限表
-- =====================================================
CREATE TABLE IF NOT EXISTS user_permissions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL COMMENT '关联用户表',
    permission_key VARCHAR(50) NOT NULL COMMENT '权限标识，如 page1, page2, page3, page4',
    UNIQUE KEY uk_user_perm (user_id, permission_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户页面权限表';

-- 给 admin 用户添加默认权限
INSERT IGNORE INTO user_permissions (user_id, permission_key) VALUES
(1, 'page1'),
(1, 'page2'),
(1, 'page3'),
(1, 'page4');

SELECT 'Docker 初始化完成! 所有表创建成功' AS MESSAGE;
