-- =====================================================
-- 工装管理系统数据库表创建 SQL
-- 数据库类型：MySQL
-- 字符集：utf8mb4
-- =====================================================

-- 删除表（如果需要重新创建）
DROP TABLE IF EXISTS T_COMPONENTS_ATT;
DROP TABLE IF EXISTS T_COMPONENTS_OPINION;
DROP TABLE IF EXISTS T_COMPONENTS_LINE;
DROP TABLE IF EXISTS T_COMPONENTS;
DROP TABLE IF EXISTS T_UNIT;
DROP TABLE IF EXISTS T_COMPANY;
DROP TABLE IF EXISTS T_DEPT;
DROP TABLE IF EXISTS T_PROJECT;

-- =====================================================
-- 1. 单位表 T_UNIT
-- =====================================================
CREATE TABLE T_UNIT (
    GUID VARCHAR(64) PRIMARY KEY COMMENT 'GUID',
    UNT_DESC VARCHAR(50) NOT NULL COMMENT '单位描述',
    UNT_TYPE VARCHAR(20) COMMENT '单位类型',
    ACTIVATION VARCHAR(2) DEFAULT 'Y' COMMENT '是否有效(Y:是,N:否)',
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='单位表';

-- 插入默认单位数据
INSERT INTO T_UNIT (GUID, UNT_DESC, UNT_TYPE, ACTIVATION) VALUES
(UUID(), '个', 'QUANTITY', 'Y'),
(UUID(), '件', 'QUANTITY', 'Y'),
(UUID(), '套', 'QUANTITY', 'Y'),
(UUID(), '台', 'QUANTITY', 'Y'),
(UUID(), '千克', 'WEIGHT', 'Y'),
(UUID(), '米', 'LENGTH', 'Y'),
(UUID(), '平方米', 'AREA', 'Y');

-- =====================================================
-- 2. 公司表 T_COMPANY
-- =====================================================
CREATE TABLE T_COMPANY (
    GUID VARCHAR(64) PRIMARY KEY COMMENT 'GUID',
    COMPANY_NO VARCHAR(20) NOT NULL UNIQUE COMMENT '公司编码',
    COMPANY_DESC VARCHAR(100) NOT NULL COMMENT '公司描述',
    COMPANY_EN_DESC VARCHAR(100) COMMENT '公司英文描述',
    ACTIVATION VARCHAR(2) DEFAULT 'Y' COMMENT '是否有效(Y:是,N:否)',
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='公司表';

-- 插入默认公司数据
INSERT INTO T_COMPANY (GUID, COMPANY_NO, COMPANY_DESC, COMPANY_EN_DESC, ACTIVATION) VALUES
(UUID(), 'COMP001', '公司1', 'Company 1', 'Y'),
(UUID(), 'COMP002', '公司2', 'Company 2', 'Y');

-- =====================================================
-- 3. 部门表 T_DEPT
-- =====================================================
CREATE TABLE T_DEPT (
    GUID VARCHAR(64) PRIMARY KEY COMMENT 'GUID',
    ORGN_CD VARCHAR(20) NOT NULL UNIQUE COMMENT '部门编码',
    ORGN_DESC VARCHAR(100) NOT NULL COMMENT '部门描述',
    SUPER_ORGN_CD VARCHAR(20) COMMENT '上级部门编码',
    ORGN_TYPE VARCHAR(2) DEFAULT '02' COMMENT '组织类型(01:公司,02:部门)',
    ACTIVATION VARCHAR(2) DEFAULT 'Y' COMMENT '是否有效(Y:是,N:否)',
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='部门表';

-- 插入默认部门数据
INSERT INTO T_DEPT (GUID, ORGN_CD, ORGN_DESC, SUPER_ORGN_CD, ORGN_TYPE, ACTIVATION) VALUES
(UUID(), 'DEPT001', '技术部', 'COMP001', '02', 'Y'),
(UUID(), 'DEPT002', '生产部', 'COMP001', '02', 'Y'),
(UUID(), 'DEPT003', '质量部', 'COMP001', '02', 'Y');

-- =====================================================
-- 4. 项目表 T_PROJECT
-- =====================================================
CREATE TABLE T_PROJECT (
    GUID VARCHAR(64) PRIMARY KEY COMMENT 'GUID',
    CODE VARCHAR(50) NOT NULL UNIQUE COMMENT '项目编码',
    PROJ_DESC VARCHAR(200) COMMENT '项目描述',
    ACTIVATION VARCHAR(2) DEFAULT 'Y' COMMENT '是否有效(Y:是,N:否)',
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='项目表';

-- 插入默认项目数据
INSERT INTO T_PROJECT (GUID, CODE, PROJ_DESC, ACTIVATION) VALUES
(UUID(), 'PROJ001', '项目1', 'Y'),
(UUID(), 'PROJ002', '项目2', 'Y'),
(UUID(), 'PROJ003', '项目3', 'Y');

-- =====================================================
-- 5. 工装申请表 T_COMPONENTS
-- =====================================================
CREATE TABLE T_COMPONENTS (
    GUID VARCHAR(64) PRIMARY KEY COMMENT 'GUID',
    BILL_NO VARCHAR(50) NOT NULL UNIQUE COMMENT '申请单号',
    COMPANY_NO VARCHAR(20) COMMENT '公司编码',
    DEPT_NO VARCHAR(20) COMMENT '部门编码',
    COMPONENTS_NAME VARCHAR(200) COMMENT '项目名称',
    PROJ_NO VARCHAR(50) COMMENT '工程号',
    DIV_CD VARCHAR(2) COMMENT '工装类别(01:生产通用,02:生产专用,03:安措,04:科研通用,05:科研专用)',
    NUMBER_NO DECIMAL(10,2) DEFAULT 0 COMMENT '需求数',
    FINAL_NUMBER_NO DECIMAL(10,2) DEFAULT 0 COMMENT '最终下发数',
    APPOINT_DUTY_DEPT_YN VARCHAR(2) DEFAULT 'N' COMMENT '是否指定责任部门(Y:是,N:否)',
    DWGNO VARCHAR(50) COMMENT '图号',
    MATERIAL_TOTAL_COST VARCHAR(50) DEFAULT '0' COMMENT '材料费用/元',
    MH_BDGT VARCHAR(50) COMMENT '预估工时/小时',
    CREATE_USER_ID VARCHAR(50) COMMENT '创建人',
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
    NEED_DATE DATE COMMENT '需求日期',
    UPDATE_USER_ID VARCHAR(50) COMMENT '更新人',
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
    REMARK VARCHAR(500) COMMENT '备注',
    MA_PROCESS_ID VARCHAR(64) COMMENT '审批流程ID',
    MA_STATUS VARCHAR(2) DEFAULT '01' COMMENT '状态(01:编制,02:已提交,03:审批中,04:已审批,05:已驳回)',
    TEL VARCHAR(20) COMMENT '联系方式',
    APP_DATE DATE COMMENT '申请日期',
    DESIGN_STATUS VARCHAR(2) COMMENT '设计状态',
    BO_ID VARCHAR(64) COMMENT '业务对象ID',
    INDEX IDX_BILL_NO (BILL_NO),
    INDEX IDX_COMPANY_NO (COMPANY_NO),
    INDEX IDX_MA_STATUS (MA_STATUS),
    INDEX IDX_CREATE_DATE (CREATE_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='工装申请表';

-- =====================================================
-- 6. 工装申请明细表 T_COMPONENTS_LINE
-- =====================================================
CREATE TABLE T_COMPONENTS_LINE (
    GUID VARCHAR(64) PRIMARY KEY COMMENT 'GUID',
    COMPONENTS_ID VARCHAR(64) NOT NULL COMMENT '工装申请ID',
    ACTIVATION VARCHAR(2) DEFAULT 'Y' COMMENT '是否有效(Y:是,N:否)',
    MATERIAL_NO VARCHAR(50) COMMENT '物资编码',
    MATERIAL_NAME VARCHAR(200) COMMENT '物资描述',
    UNIT VARCHAR(64) COMMENT '单位GUID',
    DEMAND_QTY DECIMAL(10,2) DEFAULT 0 COMMENT '需求数',
    FINAL_DEMAND_QTY DECIMAL(10,2) DEFAULT 0 COMMENT '最终需求数',
    MATERIAL_COST DECIMAL(10,2) DEFAULT 0 COMMENT '预估金额/元',
    MATERIAL_SOURCES VARCHAR(2) COMMENT '物资来源(01:采购,02:库存,03:自制)',
    REMARK VARCHAR(500) COMMENT '备注',
    QUALITY VARCHAR(50) COMMENT '材质',
    THK1 DECIMAL(10,2) COMMENT 'T1',
    THK2 DECIMAL(10,2) COMMENT 'T2',
    W1 DECIMAL(10,2) COMMENT 'B1',
    W2 DECIMAL(10,2) COMMENT 'B2',
    L DECIMAL(10,2) COMMENT 'L',
    CREATE_NODE VARCHAR(2) DEFAULT '01' COMMENT '创建节点',
    CREATE_USER_ID VARCHAR(50) COMMENT '创建人',
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
    UPDATE_USER_ID VARCHAR(50) COMMENT '更新人',
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
    BO_ID VARCHAR(64) COMMENT '业务对象ID',
    INDEX IDX_COMPONENTS_ID (COMPONENTS_ID),
    FOREIGN KEY (COMPONENTS_ID) REFERENCES T_COMPONENTS(GUID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='工装申请明细表';

-- =====================================================
-- 7. 工装申请附件表 T_COMPONENTS_ATT
-- =====================================================
CREATE TABLE T_COMPONENTS_ATT (
    GUID VARCHAR(64) PRIMARY KEY COMMENT 'GUID',
    COMPONENTS_ID VARCHAR(64) NOT NULL COMMENT '工装申请ID',
    FILE_NAME VARCHAR(200) NOT NULL COMMENT '文件名称',
    FILE_PATH VARCHAR(500) NOT NULL COMMENT '文件路径',
    FILE_SIZE VARCHAR(50) COMMENT '文件大小',
    FILE_TYPE VARCHAR(2) DEFAULT '01' COMMENT '附件类型',
    CREATE_USER_ID VARCHAR(50) COMMENT '上传人',
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '上传日期',
    UPDATE_USER_ID VARCHAR(50) COMMENT '更新人',
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
    REMARK VARCHAR(500) COMMENT '备注',
    INDEX IDX_COMPONENTS_ID (COMPONENTS_ID),
    FOREIGN KEY (COMPONENTS_ID) REFERENCES T_COMPONENTS(GUID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='工装申请附件表';

-- =====================================================
-- 8. 工装申请审批意见表 T_COMPONENTS_OPINION
-- =====================================================
CREATE TABLE T_COMPONENTS_OPINION (
    GUID VARCHAR(64) PRIMARY KEY COMMENT 'GUID',
    COMPONENTS_ID VARCHAR(64) NOT NULL COMMENT '工装申请ID',
    OPINION_TYPE VARCHAR(2) COMMENT '意见类型',
    OPINION_CONTENT VARCHAR(500) COMMENT '意见内容',
    AUDIT_USER_ID VARCHAR(50) COMMENT '审核人ID',
    AUDIT_USER_NAME VARCHAR(50) COMMENT '审核人姓名',
    AUDIT_DATE DATETIME COMMENT '审核时间',
    CREATE_USER_ID VARCHAR(50) COMMENT '创建人',
    CREATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
    UPDATE_USER_ID VARCHAR(50) COMMENT '更新人',
    UPDATE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
    INDEX IDX_COMPONENTS_ID (COMPONENTS_ID),
    FOREIGN KEY (COMPONENTS_ID) REFERENCES T_COMPONENTS(GUID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='工装申请审批意见表';

-- =====================================================
-- 创建索引（如果上面建表时没有创建）
-- =====================================================
-- CREATE INDEX IDX_BILL_NO ON T_COMPONENTS(BILL_NO);
-- CREATE INDEX IDX_COMPANY_NO ON T_COMPONENTS(COMPANY_NO);
-- CREATE INDEX IDX_MA_STATUS ON T_COMPONENTS(MA_STATUS);
-- CREATE INDEX IDX_CREATE_DATE ON T_COMPONENTS(CREATE_DATE);

-- =====================================================
-- 示例查询 SQL
-- =====================================================

-- 查询工装申请列表（包含部门名称）
SELECT 
    tc.*,
    d.ORGN_DESC AS DEPT_NAME
FROM T_COMPONENTS tc
LEFT JOIN T_DEPT d ON tc.DEPT_NO = d.ORGN_CD AND d.ORGN_TYPE = '02'
WHERE tc.ACTIVATION = 'Y'
ORDER BY tc.CREATE_DATE DESC;

-- 查询工装申请明细
SELECT * FROM T_COMPONENTS_LINE 
WHERE COMPONENTS_ID = '工装申请GUID' 
AND ACTIVATION = 'Y';

-- 查询工装申请附件
SELECT * FROM T_COMPONENTS_ATT 
WHERE COMPONENTS_ID = '工装申请GUID';

-- 查询工装申请审批意见
SELECT * FROM T_COMPONENTS_OPINION 
WHERE COMPONENTS_ID = '工装申请GUID'
ORDER BY CREATE_DATE DESC;

-- =====================================================
-- 存储过程：生成申请单号
-- =====================================================
DROP PROCEDURE IF EXISTS GEN_BILL_NO;
DELIMITER //
CREATE PROCEDURE GEN_BILL_NO(
    IN p_company_no VARCHAR(20),
    OUT p_bill_no VARCHAR(50)
)
BEGIN
    DECLARE v_date_str VARCHAR(8);
    DECLARE v_max_bill_no VARCHAR(50);
    DECLARE v_sequence INT DEFAULT 1;
    
    -- 获取当前日期字符串
    SET v_date_str = DATE_FORMAT(NOW(), '%Y%m%d');
    
    -- 查询当天最大的billNo
    SELECT MAX(BILL_NO) INTO v_max_bill_no
    FROM T_COMPONENTS
    WHERE BILL_NO LIKE CONCAT(p_company_no, v_date_str, '%');
    
    -- 提取流水号
    IF v_max_bill_no IS NOT NULL AND LENGTH(v_max_bill_no) >= LENGTH(CONCAT(p_company_no, v_date_str)) + 4 THEN
        SET v_sequence = CAST(SUBSTRING(v_max_bill_no, LENGTH(CONCAT(p_company_no, v_date_str)) + 1) AS UNSIGNED) + 1;
    END IF;
    
    -- 生成billNo
    SET p_bill_no = CONCAT(p_company_no, v_date_str, LPAD(v_sequence, 4, '0'));
END //
DELIMITER ;

-- 使用存储过程生成申请单号
-- CALL GEN_BILL_NO('COMP001', @bill_no);
-- SELECT @bill_no;
